[package]
name = "ggez-svg"
version = "0.1.0"
authors = ["Kyarigwo <bwielinga@iprimus.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.9.0"
